"""empty message

Revision ID: 09755d341476
Revises: f9659bb936d8
Create Date: 2025-08-29 23:10:36.430596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09755d341476'
down_revision: Union[str, Sequence[str], None] = 'f9659bb936d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('example_sentence_1', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('sentence_translation_1', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('example_sentence_2', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('sentence_translation_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'sentence_translation_2')
    op.drop_column('cards', 'example_sentence_2')
    op.drop_column('cards', 'sentence_translation_1')
    op.drop_column('cards', 'example_sentence_1')
    # ### end Alembic commands ###
