"""Add custom fields support to decks and cards

Revision ID: 151fe91484e4
Revises: e65579777249
Create Date: 2025-09-19 20:24:21.395152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151fe91484e4'
down_revision: Union[str, Sequence[str], None] = 'e65579777249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.add_column('decks', sa.Column('custom_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'custom_fields')
    op.drop_column('cards', 'custom_data')
    # ### end Alembic commands ###
