"""Add is_public column to decks table

Revision ID: 2679f75655bd
Revises: 2af637bd8286
Create Date: 2025-09-16 09:12:34.754634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2679f75655bd'
down_revision: Union[str, Sequence[str], None] = '2af637bd8286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('decks', sa.Column('is_public', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE decks SET is_public = FALSE WHERE is_public IS NULL")
    # Make column non-nullable
    op.alter_column('decks', 'is_public', nullable=False)
    op.create_index(op.f('ix_decks_is_public'), 'decks', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decks_is_public'), table_name='decks')
    op.drop_column('decks', 'is_public')
    # ### end Alembic commands ###
