"""Remove default language for proper onboarding flow

Revision ID: 2af637bd8286
Revises: 09755d341476
Create Date: 2025-09-15 10:54:43.502944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af637bd8286'
down_revision: Union[str, Sequence[str], None] = '09755d341476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Set existing users with default 'en' language to NULL to trigger onboarding
    # This ensures users who never explicitly chose a language go through the onboarding flow
    op.execute("UPDATE users SET selected_language = NULL WHERE selected_language = 'en'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Restore 'en' as default language for users who had NULL
    op.execute("UPDATE users SET selected_language = 'en' WHERE selected_language IS NULL")

    # ### end Alembic commands ###
