"""Add last_modified column to decks table

Revision ID: e231b877ecfe
Revises: 2679f75655bd
Create Date: 2025-09-16 18:21:07.343292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e231b877ecfe'
down_revision: Union[str, Sequence[str], None] = '2679f75655bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'last_modified')
    # ### end Alembic commands ###
