"""Add original author attribution columns to decks

Revision ID: e65579777249
Revises: 2dd15f9b0b6d
Create Date: 2025-09-16 20:49:44.188099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65579777249'
down_revision: Union[str, Sequence[str], None] = '2dd15f9b0b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('original_author_name', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('copied_from_deck_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'copied_from_deck_id')
    op.drop_column('decks', 'original_author_name')
    # ### end Alembic commands ###
